[package]
name = "host"
version = "0.0.0"
edition = "2021"
links = "app"

[lib]
name = "host"
path = "src/lib.rs"
crate-type = ["staticlib", "rlib"]

[[bin]]
name = "host"
path = "src/main.rs"

[dependencies]
libc = "0.2.146"
roc_std = { path = "roc_std" }
pronto-graphics = "0.4.0"